---
version: '3'

volumes:
  postgres_data:
    driver: local

services:

  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
      - kcnet

  keycloak:
    image: quay.io/keycloak/keycloak:18.0.2
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: pass
    ports:
      - 8080:8080
      - 8443:8443
    volumes:
      - ./ssl:/etc/ssl/local
    depends_on:
      - postgres
    restart: unless-stopped
    command: start-dev --https-certificate-file=/etc/ssl/local/cert.pem --https-certificate-key-file=/etc/ssl/local/key.pem
    networks:
      - kcnet

networks:
  kcnet:
    driver: bridge
